# Generated by Django 4.1.2 on 2022-10-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_size_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user_id',
            new_name='chat_id',
        ),
    ]
