# Generated by Django 4.1.2 on 2022-10-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_id_userinfo_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.category'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.size'),
        ),
    ]
