# Generated by Django 4.1.2 on 2022-10-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
