# Generated by Django 4.1.2 on 2022-10-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.category')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.size')),
            ],
        ),
    ]
