# Generated by Django 4.1.2 on 2022-10-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_admin_interface',
            field=models.BooleanField(default=False),
        ),
    ]
