# Generated by Django 4.1.2 on 2022-10-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_config_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_waiting',
            field=models.BooleanField(default=False),
        ),
    ]
