# Generated by Django 4.1.2 on 2022-10-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_userinfo_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='waiting_id',
        ),
    ]
