# Generated by Django 4.1.2 on 2022-10-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_userinfo_waiting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.IntegerField(),
        ),
    ]
