# Generated by Django 4.1.2 on 2022-10-17 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='photo_id',
        ),
    ]
