# Generated by Django 4.1.2 on 2022-10-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_photo_product_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_id',
            field=models.CharField(max_length=255),
        ),
    ]
