# Generated by Django 4.1.2 on 2022-10-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_category_is_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeCached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('product_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcreationcache')),
            ],
        ),
    ]
