# Generated by Django 4.1.2 on 2022-10-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_productsizecached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='productcreationcache',
            name='photo_id',
        ),
        migrations.CreateModel(
            name='ProductPhotoCached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productcreationcache')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.product')),
            ],
        ),
    ]
